spring:
  profiles:
    active: deployGCP
  data:
    redis:
      host: localhost
      port: 6379
mybatis:
  configuration:
    map-underscore-to-camel-case: true #開啟駝峰命名和下劃線命名的自動轉換
server:
  port: 8080
